version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - <PATH>:/usr/src/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  postgres_data: 